dataset: casia-webface
root_path: D:/data/face/archive
description: D:/data/face/archive/casia-webface.txt
augmentation: [
    transforms.ToTensor()
    ]
device: cuda
load_model:  # Do not fill if no model to load
neg_batch_size: 32
epochs: 10
lr: 0.001
weight_decay: 0.001
log: True
log_path: D:/repos/Face_Recognition/logs
log_interval: 1
save_path: D:/repos/Face_Recognition/models