dataset: casia-webface
device: cuda

dataloader: {
    description: D:/data/face/archive/description.txt,
    neg_batch_size: 63,
}
augmentation:
    - transforms.ToTensor()
model: {
    name: iresnet50,
    num_classes: 512,
}
load_model: baseline.pth # Do not fill if no model to load
loss_fn: {
    name: FR11NArcCELoss,
    s: 64,
    margin: 0.5,
    eps: 1.0e-7,
}
epochs: 10
batch_size: 2
num_workers: 16
lr: 1.0e-5
weight_decay: 0.1
scheduler: {
    milestones: [3, 6],
    gamma: 0.1,
}

log: True
log_path: D:/repos/Face_Recognition/logs
log_interval: 1 
save_path: D:/repos/Face_Recognition/models
