dataset: casia-webface
device: cuda

dataloader: {
    mode: 11N,
    description: D:/data/face/archive/description.txt,
    neg_batch_size: 63,
}
augmentation:
    - transforms.ToTensor()
model: {
    name: iresnet50,
    num_classes: 512,
}
load_model:  # Do not fill if no model to load
loss_fn: {
    name: FR11NmmCELoss,
    temperature: 4,
}
epochs: 10
lr: 0.001
weight_decay: 0.1
scheduler: {
    milestones: [3, 6],
    gamma: 0.1,
}

log: True
log_path: D:/repos/Face_Recognition/logs
log_interval: 1 
save_path: D:/repos/Face_Recognition/models
